version: "3.7"
services:
  app:
    build:
      args:
        user: ryanpambudi
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: epro-api
    container_name: epro-api-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - epro-api

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 9000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - epro-api

networks:
  epro-api:
    driver: bridge
